const QuestionActionTypes = {
  INITIALIZE_DILEMMAS: "INITIALIZE_DILEMMAS",
  GET_QUESTION: "GET_QUESTION",
  TOGGLE_OPTIONS: "TOGGLE_OPTIONS",
  ADD_DILEMA_TO_SHOWN: "ADD_DILEMA_TO_SHOWN",
  TOGGLE_LIKE: "TOGGLE_LIKE",
  GET_COMMENTS: "GET_COMMENTS",
};

export default QuestionActionTypes;
