const QuestionActionTypes = {
  INITIALIZE_DILEMMAS: "INITIALIZE_DILEMMAS",
  GET_QUESTION: "GET_QUESTION",
  TOGGLE_OPTIONS: "TOGGLE_OPTIONS",
  ADD_DILEMA_TO_SHOWN: "ADD_DILEMA_TO_SHOWN",
  TOGGLE_LIKE: "TOGGLE_LIKE",
  GET_COMMENTS: "GET_COMMENTS",
  LIKE_AFTER_COMMENT: "LIKE_AFTER_COMMENT",
  GET_FAV_COMMENTS: "GET_FAV_COMMENTS",
  TOGGLE_FAV_LIKE: "TOGGLE_FAV_LIKE",
  RESET_FAV_LIKE: "RESET_FAV_LIKE",
};

export default QuestionActionTypes;
