const QuestionActionTypes = {
  INITIALIZE_DILEMMAS: "INITIALIZE_DILEMMAS",
  GET_QUESTION: "GET_QUESTION",
  TOGGLE_OPTIONS: "TOGGLE_OPTIONS",
  ADD_DILEMA_TO_SHOWN: "ADD_DILEMA_TO_SHOWN",
};

export default QuestionActionTypes;
